### PR TITLE
fix bip32 versions for ltc and add for dgb/doge

### PR DESCRIPTION
**Pull request by fanatid**
Any ideas from where LTC versions came?
https://github.com/cryptocoinjs/coininfo/commit/cebae8dc73992a29e238aa4903d1e5ee15761efb#diff-0db2151f14b143bd0412e30f40041748R13 ? @jprichardson ?

### CODE REVIEW

**Comment by fanatid** [comment]
Looks like current numbers came from https://github.com/satoshilabs/slips/blob/master/slip-0132.md
but source code contain bitcoin-like numbers :thinking:

**Comment by dbolser** [comment]
I'm seeing the following error when calling `coininfo.litecoin.test.toBitcoinJS()`
``` 
.../node_modules/coininfo/lib/coininfo.js:71
      public: this.versions.bip32.public,
                                 ^
TypeError: Cannot read property 'public' of undefined
    at Object.toBitcoinJS (/var/hcp4/node_modules/coininfo/lib/coininfo.js:71:34)
    at Object.<anonymous> (/home/dmb/dans-test.js:19:24)
    at Module._compile (module.js:571:32)
    ...
```

Is that what this patch fixes?

**Comment by reeZee3U** [comment]
> I'm seeing the following error when calling `coininfo.litecoin.test.toBitcoinJS()`
> 
> ```
> .../node_modules/coininfo/lib/coininfo.js:71
>       public: this.versions.bip32.public,
>                                  ^
> TypeError: Cannot read property 'public' of undefined
>     at Object.toBitcoinJS (/var/hcp4/node_modules/coininfo/lib/coininfo.js:71:34)
>     at Object.<anonymous> (/home/dmb/dans-test.js:19:24)
>     at Module._compile (module.js:571:32)
>     ...
> ```
> Is that what this patch fixes?

The same goes with coininfo.dogecoin.test.toBitcoinJS()

**Comment by junderw** [comment]
re-open if needed.

**Pull request closed without merging**
