### PR TITLE
bip44-constants

### LINKED ISSUE #18: Remove bip44 constants.
They are defined here: https://github.com/bitcoinjs/bip44-constants It's redundant to have them in two places.

### PR DESCRIPTION
**Pull request by fanatid**
Resolve #18

### CODE REVIEW

**Comment by jprichardson** [comment]
Thanks. Do you think that it makes sense to just remove the bip44 constants altogether? i.e. Just encourage people to use `bip44-constants`?

**Comment by fanatid** [comment]
> Do you think that it makes sense to just remove the bip44 constants altogether? i.e. Just encourage people to use `bip44-constants`?

Not sure. I think use all information about coin from one place it's nice.

**Comment by fanatid** [comment]
@jprichardson you don't forget about this PR?
probably this PR need major bump, because I change some coin names for consistent with bip44-constants

**Comment by jprichardson** [comment]
Do we want to return the number with the `'` or without? e.g. for Dogecoin, should we be returning:

`bip44Constants.Dogecoin - 0x80000000` or `bip44Constants.Dogecoin`

??

**Comment by fanatid** [comment]
Why you want this? [SLIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md#registered-coin-types) has numbers with `'`

**Comment by jprichardson** [comment]
> Why you want this? SLIP-0044 has numbers with '

Exactly. Since when you pass the constant to a `derive()` function, you typically need the `'` (bip44Constants.Dogecoin) instead of (bip44Constants.Dogecoin + 0x80000000).

But since all have `0x80000000`, it could make it hard to detect differences. IDK, I'm probably splitting hairs here.

**Comment by fanatid** [comment]
maybe return two constants? one with `'` and one without `'`?

**Comment by jprichardson** [comment]
Hmmm, still thinking about this.

**Pull request closed without merging**
