### PR TITLE
Update doge.js bip32

### PR DESCRIPTION
**Pull request by vipertechofficial**

### CODE REVIEW

**Comment by junderw** [comment]
Please link to the source where this is included in dogecoin. Thanks.

**Comment by vipertechofficial** [comment]
@junderw Unfortunately it comes from https://gist.github.com/Anderson-Juhasc/e6975cc51116742b650d1d9cefffa4af
Hopefully it works on wallet.crypto.red with theses parameters.

**Comment by vipertechofficial** [comment]
@junderw https://github.com/bip32JP/bip32JP.github.io/blob/master/js/bip32.js
Is that a trusted source?

**Comment by junderw** [comment]
The gist you posted and bip32jp are different.

the gist is "tpub" and bip32jp is "tgub" for the extended pubkey.

**Comment by vipertechofficial** [comment]
I am sure that the gist is okay,
On the app I develop it works: https://github.com/crypto-red/crypto-red.github.io/blob/master/src/js/utils/api-doge.js
Yet, it can work and be wrong at the same time, but yeah, ...

**Comment by vipertechofficial** [comment]
But in the dogecoin repository there isn't the private or public key that is present in it (for testnet) so I may wonder where we could find it elsewhere.

**Pull request closed without merging**
