### PR TITLE
Added NuBits

### PR DESCRIPTION
**Pull request by jgeewax**

### CODE REVIEW

**Comment by jprichardson** [comment]
Awesome, thanks! But it doesn't actually get included... as seen here: https://github.com/cryptocoinjs/coininfo/blob/master/lib/coininfo.js#L2

**Comment by jgeewax** [comment]
Whoops my bad. Let me fix that and send to you tomorrow morning :)

**Comment by jgeewax** [comment]
OK -- let me know if this works @jprichardson ?

**Comment by jprichardson** [comment]
Thanks!

**Pull request merged**
