### PR TITLE
update Dash values to match 0.12.1 release

### PR DESCRIPTION
**Pull request by UdjinM6**
References:
- dns seeds https://github.com/dashpay/dash/pull/1395
- testnet pubkey version https://github.com/dashpay/dash/pull/767/files#diff-64cbe1ad5465e13bc59ee8bb6f3de2e7R222
- bip32 https://github.com/dashpay/dash/pull/926

### CODE REVIEW

**Comment by jprichardson** [comment]
Thanks!

**Comment by gpip** [comment]
@UdjinM6 is it ok to continue using the old bytes for bip32? bitcore-lib gets confused with this dup from bitcoin, e.g.:

```
> var b = require('bitcore-lib');
> var c = require('coininfo');
> var dashmain = c.dash.main.toBitcore();
> dashmain.name = 'dash';
> dashmain.alias = 'dashmainnet';
> b.Networks.add(dashmain);
> b.HDPrivateKey('dash').network
'dash'  # OK
> b.HDPrivateKey(b.Networks.mainnet).network
'dash'  # FAIL
```

Without modifying:

```
> var b = require('bitcore-lib');
> b.HDPrivateKey(b.Networks.mainnet).network.name
'livenet'  # OK
```

**Comment by UdjinM6** [comment]
@gpip We had a conversation with multi-coin wallet devs (Jaxx, Exodus) and turned out that none of them are using `pure` bip32, they see bip32 as coin-agnostic bip and use bip44 to produce coin-specific keys, so we decided to adopt this policy in our reference client as well.

Litecoin values were changed this way too btw (https://www.reddit.com/r/litecoin/comments/48wd2e/why_arent_the_litecoin_bip32_serialization_values/) and they don't match now:
- reference client https://github.com/litecoin-project/litecoin/blob/master/src/chainparams.cpp#L131-L132
- this lib https://github.com/cryptocoinjs/coininfo/blob/master/lib/coins/ltc.js#L25-L26

**Comment by gpip** [comment]
@UdjinM6 even if they don't use pure bip32, this change still breaks bitcore-lib (see https://github.com/bitpay/bitcore-lib/issues/131). You also can't use two bitcore-lib instances as there are checks against that (so you couldn't use bitcore-dash-lib and bitcore-lib to handle this issue). Seems like a good idea to patch bitcore-lib to handle duplicates on network settings correctly.

**Comment by UdjinM6** [comment]
@gpip
>Seems like a good idea to patch bitcore-lib to handle duplicates on network settings correctly.

I agree

**Comment by jprichardson** [comment]
Yeah, per BIP43 recommendations: https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki#node-serialization we (Exodus) uses `xpub` and `xpriv` for all assets.

**Pull request merged**
