### PR TITLE
update Dash info

### PR DESCRIPTION
**Pull request by UdjinM6**
- update mainnet to use hex values (to follow btc style)
- fix testnet params

### CODE REVIEW

**Comment by jprichardson** [comment]
When did this change happen?

**Comment by UdjinM6** [comment]
Err.. Which one? Testnet params here are broken now for some reason and I just modified them to use correct values... https://github.com/dashpay/dash/blob/master/src/chainparams.cpp#L237-L241

**Comment by gpip** [comment]
Maybe I'm misreading this but shouldn't the pubkey addr byte be `0x8c` (140) instead of `0x8b` (139)?

**Comment by UdjinM6** [comment]
@gpip yep, testnet pubkey version changed in 12.1 release. #28 should fix it.

**Pull request merged**
